# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.roastLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.roastLabel.setObjectName("roastLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roastLabel)
        self.roastCombo = QtWidgets.QComboBox(AddEditCoffeeForm)
        self.roastCombo.setObjectName("roastCombo")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roastCombo)
        self.typeLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeCombo = QtWidgets.QComboBox(AddEditCoffeeForm)
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeCombo)
        self.tasteLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.tasteLabel.setObjectName("tasteLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tasteLabel)
        self.tasteEdit = QtWidgets.QTextEdit(AddEditCoffeeForm)
        self.tasteEdit.setObjectName("tasteEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tasteEdit)
        self.priceLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.priceSpin = QtWidgets.QDoubleSpinBox(AddEditCoffeeForm)
        self.priceSpin.setMinimum(0.0)
        self.priceSpin.setMaximum(10000.0)
        self.priceSpin.setObjectName("priceSpin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.priceSpin)
        self.volumeLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.volumeLabel.setObjectName("volumeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.volumeLabel)
        self.volumeSpin = QtWidgets.QSpinBox(AddEditCoffeeForm)
        self.volumeSpin.setMinimum(1)
        self.volumeSpin.setMaximum(5000)
        self.volumeSpin.setObjectName("volumeSpin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volumeSpin)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddEditCoffeeForm)
        self.cancelButton.clicked.connect(AddEditCoffeeForm.reject) # type: ignore
        self.saveButton.clicked.connect(AddEditCoffeeForm.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Coffee Information"))
        self.nameLabel.setText(_translate("AddEditCoffeeForm", "Coffee Name:"))
        self.roastLabel.setText(_translate("AddEditCoffeeForm", "Roast Level:"))
        self.roastCombo.setItemText(0, _translate("AddEditCoffeeForm", "Light"))
        self.roastCombo.setItemText(1, _translate("AddEditCoffeeForm", "Medium"))
        self.roastCombo.setItemText(2, _translate("AddEditCoffeeForm", "Medium-Dark"))
        self.roastCombo.setItemText(3, _translate("AddEditCoffeeForm", "Dark"))
        self.typeLabel.setText(_translate("AddEditCoffeeForm", "Type:"))
        self.typeCombo.setItemText(0, _translate("AddEditCoffeeForm", "beans"))
        self.typeCombo.setItemText(1, _translate("AddEditCoffeeForm", "ground"))
        self.tasteLabel.setText(_translate("AddEditCoffeeForm", "Taste Description:"))
        self.priceLabel.setText(_translate("AddEditCoffeeForm", "Price (₽):"))
        self.volumeLabel.setText(_translate("AddEditCoffeeForm", "Volume (g):"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Save"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Cancel"))
